### ISSUE TITLE
Missing Materials

### ISSUE THREAD

**Issue by valzargaming** [VZGCoders/TOTK-Recipe-Calculator#5]
There's only about 92 materials added so far. The data dump was missing information when I made the initial prototype. Echocolat confirmed that every item listen on the Materials tab is a valid cooking item, however enemy part data for EffectLevel, EffectType, EffectiveTime, and HitPointRecovery did not get captured by their script. After these values have been added the ingredients list needs to be recreated.

Data dump: https://docs.google.com/spreadsheets/d/18pNtDx3z-8CwGJRmlW574xbQ6VphQOkvpZhClpOEVDA/edit#gid=704906736

**Comment by Rattlesire** [comment]
Did he happen to mention why there are multiple copies of a recipe?

**Comment by valzargaming** [comment]
Nintendo being Nintendo

**Comment by valzargaming** [comment]
I reached out to Echocolat on Discord again this morning. For now they're on holidays but would be glad to upload their data dumps as CSVs to GitHub after they fix their scripts and after their holidays. Once that has been updated I'll include their dumps as dependencies for this project so we can always be up to date with the latest info.

**Comment by valzargaming** [comment]
We are currently working on a modified version of Echocolat's data dump and have generated our own CSVs to account for the various confirmed formulas we have so far. This issue can be closed once we have confirmed that we have added all missing materials to our CSVs.
